### ISSUE TITLE
App got rejected due to MANAGE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by osama-alshanti** [mehdiyari/Fallery#21]

**Comment by or-else** [comment]
Google Play Store restricts use of `MANAGE_EXTERNAL_STORAGE` to apps which specifically manage storage, such as file managers. If the app is not a file manager, it should not request MANAGE_EXTERNAL_STORAGE` permission:

Quote from https://developer.android.com/about/versions/11/privacy/storage
*Note: If you publish your app to Google Play, carefully read the [notice](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play). If you target Android 11 and declare All files access, __it can affect your ability to publish and update your app on Google Play.__*


Fallery requests and uses `MANAGE_EXTERNAL_STORAGE` (All files access) which makes it difficult to use it in apps.

Why is it needed? Do you really have to request `MANAGE_EXTERNAL_STORAGE`? For example, I do not know any other apps with media pickers requesting this permission.

**Comment by or-else** [comment]
Essentially, your widget should not require this permission. It should function with it. Otherwise it cannot be used by most apps.

**Comment by mehdiyari** [comment]
Hi @or-else, Sorry for the late response; it's resolved on #25 and will be released ASAP.
